@url = http://localhost:21370

###

GET {{url}}/categories HTTP/1.1

###

@categoryIdToGet = 1BC93A6B-288B-4A3F-9A39-6A2D0F71A75A

GET {{url}}/categories/{{categoryIdToGet}} HTTP/1.1

###

POST {{url}}/categories HTTP/1.1
Content-Type: application/json

{
    "name": "Category 3"
}

###

@categoryIdToRemove = D7F14633-68C1-466A-8F9D-002962183F44
DELETE  {{url}}/categories/{{categoryIdToRemove}} HTTP/1.1