@url = http://localhost:21370

###

GET {{url}}/offers HTTP/1.1

###

@offerIdToGet = 9FF1DCCD-EC85-404B-951A-FC982721638D

GET {{url}}/offers/{{offerIdToGet}} HTTP/1.1

###

@categoryId = 881C44A7-95DB-4274-958E-5DBBCFFADE21

POST {{url}}/offers HTTP/1.1
Content-Type: application/json

{
    "name": "Offer 2",
    "price": 21.37,
    "stock": 22,
    "category": {
        "id": "{{categoryId}}"
    }
}

###

@offerIdToRemove = E7C4935F-7C75-4035-935D-4D6AFD2F64F5
DELETE  {{url}}/offers/{{offerIdToRemove}} HTTP/1.1